/* ═══════════════════════════════════════════════════
   questions_easy.js — Preguntas de dificultad FÁCIL
   diff: "easy"

   Para añadir preguntas fáciles:
     {q:"pregunta", a:["op1","op2","op3","op4"], c:índice_correcto, cat:"cat", diff:"easy"}

   Categorías disponibles: geo, sci, hist, art, sport, ent, food, tech
═══════════════════════════════════════════════════ */

const QUESTIONS_EASY = [
  // ── GEOGRAFÍA ──
  {q:"¿Cuál es el río más largo del mundo?",          a:["Nilo","Amazonas","Yangtsé","Misisipi"],          c:0, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es el país más grande del mundo?",         a:["Canadá","China","EE.UU.","Rusia"],              c:3, cat:"geo",  diff:"easy"},
  {q:"¿En qué continente está Egipto?",               a:["Asia","Europa","África","Oceanía"],              c:2, cat:"geo",  diff:"easy"},
  {q:"¿Cuántos continentes hay en la Tierra?",         a:["5","6","7","8"],                                c:2, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es la capital de Japón?",                 a:["Osaka","Kioto","Tokio","Hiroshima"],             c:2, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es el océano más grande?",                a:["Atlántico","Índico","Ártico","Pacífico"],        c:3, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es la montaña más alta del mundo?",       a:["K2","Monte Everest","Aconcagua","Mont Blanc"],   c:1, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es el elemento con símbolo Au?",           a:["Plata","Oro","Aluminio","Argón"],                c:1, cat:"sci",  diff:"easy"},
  {q:"¿Cuántos planetas tiene el Sistema Solar?",      a:["7","8","9","10"],                               c:1, cat:"sci",  diff:"easy"},
  {q:"¿A qué temperatura hierve el agua al nivel del mar?",a:["90°C","95°C","100°C","105°C"],              c:2, cat:"sci",  diff:"easy"},
  {q:"¿Qué gas es más abundante en la atmósfera?",     a:["Oxígeno","CO₂","Nitrógeno","Argón"],            c:2, cat:"sci",  diff:"easy"},
  {q:"¿Qué planeta es el más cercano al Sol?",         a:["Venus","Tierra","Marte","Mercurio"],             c:3, cat:"sci",  diff:"easy"},
  {q:"¿Cuál es el planeta más grande del Sistema Solar?",a:["Saturno","Júpiter","Urano","Neptuno"],        c:1, cat:"sci",  diff:"easy"},
  {q:"¿Cuántos colores tiene el arco iris?",           a:["5","6","7","8"],                                c:2, cat:"sci",  diff:"easy"},
  {q:"¿Cuál es el elemento más ligero de la tabla periódica?",a:["Helio","Hidrógeno","Litio","Boro"],      c:1, cat:"sci",  diff:"easy"},
  // ── HISTORIA ──
  {q:"¿En qué año llegó el hombre a la Luna?",         a:["1965","1969","1972","1961"],                     c:1, cat:"hist", diff:"easy"},
  {q:"¿Quién fue el primer presidente de EE.UU.?",     a:["Lincoln","Jefferson","Washington","Franklin"],   c:2, cat:"hist", diff:"easy"},
  {q:"¿En qué año comenzó la Primera Guerra Mundial?", a:["1908","1912","1914","1916"],                     c:2, cat:"hist", diff:"easy"},
  {q:"¿Quién pintó la Mona Lisa?",                     a:["Miguel Ángel","Rafael","Da Vinci","Botticelli"], c:2, cat:"hist", diff:"easy"},
  {q:"¿Quién escribió Don Quijote de la Mancha?",      a:["Lope de Vega","Quevedo","Cervantes","Calderón"],c:2, cat:"hist", diff:"easy"},
  {q:"¿Qué civilización construyó Machu Picchu?",      a:["Maya","Azteca","Inca","Olmeca"],                 c:2, cat:"hist", diff:"easy"},
  {q:"¿En qué año terminó la Segunda Guerra Mundial?", a:["1943","1944","1945","1946"],                     c:2, cat:"hist", diff:"easy"},
  {q:"¿Quién descubrió América para Europa en 1492?",  a:["Vasco da Gama","Américo Vespucio","Colón","Magallanes"],c:2,cat:"hist",diff:"easy"},
  {q:"¿Quién fue el primer ser humano en el espacio?", a:["Neil Armstrong","Yuri Gagarin","Buzz Aldrin","Alan Shepard"],c:1,cat:"hist",diff:"easy"},
  // ── ARTE Y CULTURA ──
  {q:"¿En qué país se originó el yoga?",               a:["China","Japón","India","Nepal"],                 c:2, cat:"art",  diff:"easy"},
  {q:"¿En qué país se inventó la pizza?",              a:["España","Francia","Italia","Grecia"],            c:2, cat:"art",  diff:"easy"},
  {q:"¿Quién compuso la Quinta Sinfonía?",             a:["Mozart","Vivaldi","Beethoven","Bach"],           c:2, cat:"art",  diff:"easy"},
  {q:"¿Qué escritor creó a Sherlock Holmes?",          a:["Agatha Christie","Arthur Conan Doyle","Edgar Allan Poe","Mark Twain"],c:1,cat:"art",diff:"easy"},
  {q:"¿Qué arquitecto diseñó la Sagrada Familia?",     a:["Santiago Calatrava","Mies van der Rohe","Gaudí","Piano"],c:2,cat:"art",diff:"easy"},
  // ── DEPORTE ──
  {q:"¿Cuántos jugadores hay en un equipo de fútbol?", a:["9","10","11","12"],                              c:2, cat:"sport",diff:"easy"},
  {q:"¿Cada cuántos años se celebra el Mundial de fútbol?",a:["2","4","6","8"],                            c:1, cat:"sport",diff:"easy"},
  {q:"¿Qué país ha ganado más Mundiales de fútbol?",   a:["Alemania","Argentina","Italia","Brasil"],        c:3, cat:"sport",diff:"easy"},
  {q:"¿Cuántos anillos tiene el símbolo olímpico?",    a:["4","5","6","7"],                                c:1, cat:"sport",diff:"easy"},
  {q:"¿Cuántos metros mide una piscina olímpica?",     a:["25m","50m","75m","100m"],                       c:1, cat:"sport",diff:"easy"},
  {q:"¿Qué deporte practica Rafa Nadal?",              a:["Golf","Padel","Tenis","Squash"],                 c:2, cat:"sport",diff:"easy"},
  // ── ENTRETENIMIENTO ──
  {q:"¿Quién interpreta a Iron Man en el MCU?",        a:["Chris Evans","Chris Pratt","Robert Downey Jr.","Benedict Cumberbatch"],c:2,cat:"ent",diff:"easy"},
  {q:"¿Qué personaje dice 'Yo soy tu padre'?",         a:["Obi-Wan Kenobi","Yoda","Darth Vader","Kylo Ren"],c:2,cat:"ent", diff:"easy"},
  {q:"¿Qué animal es Simba en El Rey León?",           a:["Leopardo","Guepardo","León","Tigre"],            c:2, cat:"ent",  diff:"easy"},
  {q:"¿En qué saga aparece Hogwarts?",                 a:["El señor de los anillos","Narnia","Harry Potter","Crónicas de Rin"],c:2,cat:"ent",diff:"easy"},
  {q:"¿Quién canta 'Bohemian Rhapsody'?",              a:["Led Zeppelin","The Beatles","Queen","Rolling Stones"],c:2,cat:"ent",diff:"easy"},
  {q:"¿Qué empresa creó Minecraft?",                   a:["EA","Activision","Mojang","Ubisoft"],            c:2, cat:"ent",  diff:"easy"},
  {q:"¿Cuántas películas hay en la trilogía original de Star Wars?",a:["2","3","4","6"],                    c:1, cat:"ent",  diff:"easy"},
  {q:"¿Qué plataforma lanzó la serie 'Stranger Things'?",a:["HBO","Disney+","Amazon","Netflix"],            c:3, cat:"ent",  diff:"easy"},
  // ── GASTRONOMÍA ──
  {q:"¿De qué país es el sushi?",                      a:["China","Corea","Japón","Vietnam"],               c:2, cat:"food", diff:"easy"},
  {q:"¿Cuál es el ingrediente principal del guacamole?",a:["Tomate","Aguacate","Cebolla","Cilantro"],       c:1, cat:"food", diff:"easy"},
  {q:"¿De qué país es la paella?",                     a:["Italia","México","España","Portugal"],           c:2, cat:"food", diff:"easy"},
  {q:"¿Qué vino se produce en La Rioja?",              a:["Albariño","Ribera del Duero","Rioja","Priorat"], c:2, cat:"food", diff:"easy"},
  {q:"¿De qué fruta se hace el vino?",                 a:["Manzana","Uva","Melocotón","Cereza"],            c:1, cat:"food", diff:"easy"},
  // ── TECNOLOGÍA ──
  {q:"¿Cuántos bits tiene un byte?",                   a:["4","8","16","32"],                               c:1, cat:"tech", diff:"easy"},
  {q:"¿Quién fundó Microsoft?",                        a:["Steve Jobs","Elon Musk","Bill Gates","Mark Zuckerberg"],c:2,cat:"tech",diff:"easy"},
  {q:"¿Qué empresa creó el sistema operativo Android?",a:["Apple","Microsoft","Google","Samsung"],          c:2, cat:"tech", diff:"easy"},
  {q:"¿Cuántos núcleos tiene un procesador 'quad-core'?",a:["2","4","6","8"],                              c:1, cat:"tech", diff:"easy"},
  // ── MATEMÁTICAS / MISC ──
  {q:"¿Cuántos lados tiene un hexágono?",              a:["5","6","7","8"],                                 c:1, cat:"sci",  diff:"easy"},
  {q:"¿Cuántos metros tiene un kilómetro?",            a:["100","500","1000","10000"],                      c:2, cat:"sci",  diff:"easy"},
  {q:"¿Cuántos años dura una década?",                 a:["5","10","20","100"],                             c:1, cat:"hist", diff:"easy"},
  {q:"¿Cuántos días tiene un año bisiesto?",           a:["364","365","366","367"],                         c:2, cat:"sci",  diff:"easy"},
  {q:"¿Cuál es el animal terrestre más rápido?",       a:["León","Guepardo","Caballo","Halcón"],            c:1, cat:"sci",  diff:"easy"},
  {q:"¿Cuántas semanas tiene un año?",                 a:["48","50","52","54"],                             c:2, cat:"sci",  diff:"easy"},
  {q:"¿Cuántos ceros tiene un millón?",                a:["5","6","7","8"],                                 c:1, cat:"sci",  diff:"easy"},
  // ── GEOGRAFÍA (nuevas) ──
  {q:"¿Cuál es la capital de Argentina?",              a:["Córdoba","Rosario","Buenos Aires","Mendoza"],    c:2, cat:"geo",  diff:"easy"},
  {q:"¿En qué continente está Madagascar?",            a:["Asia","Oceanía","América","África"],             c:3, cat:"geo",  diff:"easy"},
  {q:"¿Qué país tiene forma de bota?",                 a:["Grecia","España","Italia","Portugal"],           c:2, cat:"geo",  diff:"easy"},
  {q:"¿En qué país está el Taj Mahal?",                a:["Pakistán","India","Bangladesh","Nepal"],         c:1, cat:"geo",  diff:"easy"},
  {q:"¿Qué estrecho separa España de Marruecos?",      a:["Bósforo","Gibraltar","Ormuz","Magallanes"],      c:1, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es la capital de Noruega?",                a:["Bergen","Estocolmo","Helsinki","Oslo"],          c:3, cat:"geo",  diff:"easy"},
  {q:"¿Qué mar baña las costas de España al sur?",     a:["Mar Negro","Mar del Norte","Mar Mediterráneo","Mar Báltico"],c:2,cat:"geo",diff:"easy"},
  // ── CIENCIA (nuevas) ──
  {q:"¿Cuántas cámaras tiene el corazón humano?",      a:["2","3","4","5"],                                 c:2, cat:"sci",  diff:"easy"},
  {q:"¿Qué vitamina produce el sol en la piel?",       a:["Vitamina A","Vitamina B12","Vitamina C","Vitamina D"],c:3,cat:"sci",diff:"easy"},
  {q:"¿Qué fuerza mantiene a la Luna en órbita?",      a:["Magnetismo","Gravedad","Fricción","Electromagnetismo"],c:1,cat:"sci",diff:"easy"},
  {q:"¿Cuántas fases tiene la Luna?",                  a:["2","4","6","8"],                                 c:1, cat:"sci",  diff:"easy"},
  {q:"¿Qué gas expiramos principalmente al respirar?", a:["Oxígeno","Nitrógeno","CO₂","Vapor de agua"],     c:2, cat:"sci",  diff:"easy"},
  {q:"¿Cuántos dientes tiene un adulto humano?",       a:["28","30","32","34"],                             c:2, cat:"sci",  diff:"easy"},
  {q:"¿Qué planeta tiene los anillos más visibles?",   a:["Júpiter","Urano","Neptuno","Saturno"],           c:3, cat:"sci",  diff:"easy"},
  {q:"¿Cuál es el punto de fusión del hielo?",         a:["-10°C","0°C","4°C","10°C"],                      c:1, cat:"sci",  diff:"easy"},
  {q:"¿Qué es la fotosíntesis?",                       a:["Alimentación animal","Conversión de luz en energía vegetal","Reproducción celular","Digestión de minerales"],c:1,cat:"sci",diff:"easy"},
  {q:"¿Qué hueso es el más largo del cuerpo humano?",  a:["Húmero","Tibia","Fémur","Radio"],                c:2, cat:"sci",  diff:"easy"},
  {q:"¿Qué tipo de energía genera un panel solar?",    a:["Química","Térmica","Eléctrica","Nuclear"],       c:2, cat:"sci",  diff:"easy"},
  {q:"¿En qué año comenzó la Segunda Guerra Mundial?", a:["1937","1938","1939","1940"],                     c:2, cat:"hist", diff:"easy"},
  {q:"¿Quién fue el primer hombre en orbitar la Tierra?",a:["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","Alan Shepard"],c:2,cat:"hist",diff:"easy"},
  {q:"¿Qué civilización construyó el Coliseo de Roma?",a:["Griega","Romana","Etrusca","Cartaginesa"],       c:1, cat:"hist", diff:"easy"},
  {q:"¿En qué país se originó el nazismo?",            a:["Italia","Austria","Alemania","Rusia"],           c:2, cat:"hist", diff:"easy"},
  {q:"¿Quién fue Napoleón Bonaparte?",                 a:["Rey de Francia","Emperador francés","General inglés","Zar ruso"],c:1,cat:"hist",diff:"easy"},
  {q:"¿Quién lideró la revolución cubana?",            a:["Che Guevara","Camilo Cienfuegos","Fidel Castro","Raúl Castro"],c:2,cat:"hist",diff:"easy"},
  {q:"¿Qué país lanzó las primeras bombas atómicas?",  a:["URSS","Reino Unido","EE.UU.","Francia"],         c:2, cat:"hist", diff:"easy"},
  {q:"¿Quién pintó la Capilla Sixtina?",               a:["Rafael","Da Vinci","Miguel Ángel","Botticelli"],  c:2, cat:"hist", diff:"easy"},
  // ── ARTE Y CULTURA (nuevas) ──
  {q:"¿Quién escribió 'Cien años de soledad'?",        a:["Mario Vargas Llosa","Pablo Neruda","Gabriel García Márquez","Jorge Luis Borges"],c:2,cat:"art",diff:"easy"},
  {q:"¿En qué país se originó el flamenco?",           a:["Argentina","Portugal","España","México"],        c:2, cat:"art",  diff:"easy"},
  {q:"¿Qué pintor es conocido por sus relojes blandos?",a:["Picasso","Miró","Dalí","Magritte"],             c:2, cat:"art",  diff:"easy"},
  {q:"¿Qué escritor creó a Drácula?",                  a:["Mary Shelley","H.G. Wells","Bram Stoker","Edgar Allan Poe"],c:2,cat:"art",diff:"easy"},
  {q:"¿En qué ciudad está el museo Guggenheim más famoso de España?",a:["Madrid","Barcelona","Bilbao","Valencia"],c:2,cat:"art",diff:"easy"},
  {q:"¿Quién escribió 'La Odisea'?",                   a:["Sócrates","Homero","Platón","Virgilio"],         c:1, cat:"art",  diff:"easy"},
  {q:"¿En qué ciudad está el museo del Prado?",        a:["Barcelona","Sevilla","Madrid","Valencia"],       c:2, cat:"art",  diff:"easy"},
  {q:"¿Qué artista pintó 'La noche estrellada'?",      a:["Monet","Renoir","Van Gogh","Gauguin"],           c:2, cat:"art",  diff:"easy"},
  {q:"¿Quién escribió 'El principito'?",               a:["Julio Verne","Antoine de Saint-Exupéry","Voltaire","Dumas"],c:1,cat:"art",diff:"easy"},
  // ── DEPORTE (nuevas) ──
  {q:"¿Cuántos jugadores tiene un equipo de baloncesto?",a:["4","5","6","7"],                              c:1, cat:"sport",diff:"easy"},
  {q:"¿En qué deporte se usan palos y un hoyo?",        a:["Hockey","Polo","Golf","Criquet"],               c:2, cat:"sport",diff:"easy"},
  {q:"¿Qué país ganó el Mundial de fútbol en 2022?",    a:["Francia","Brasil","Argentina","Croacia"],       c:2, cat:"sport",diff:"easy"},
  {q:"¿Cuántos jugadores tiene un equipo de voleibol?", a:["5","6","7","8"],                               c:1, cat:"sport",diff:"easy"},
  {q:"¿En qué país se originaron los Juegos Olímpicos?",a:["Roma","Egipto","Grecia","Turquía"],             c:2, cat:"sport",diff:"easy"},
  {q:"¿Cuántos metros nada un nadador en 100m libre?",  a:["50","100","200","dos largos de 50"],            c:1, cat:"sport",diff:"easy"},
  {q:"¿En qué deporte se usa el término 'slam dunk'?",  a:["Fútbol","Rugby","Baloncesto","Béisbol"],        c:2, cat:"sport",diff:"easy"},
  {q:"¿Cuánto dura un partido de fútbol reglamentario?",a:["80 min","90 min","100 min","120 min"],          c:1, cat:"sport",diff:"easy"},
  {q:"¿Qué deporte practica Pau Gasol?",                a:["Tenis","Fútbol","Baloncesto","Balonmano"],      c:2, cat:"sport",diff:"easy"},
  {q:"¿Cuántas ruedas tiene un monoplaza de Fórmula 1?",a:["3","4","6","8"],                               c:1, cat:"sport",diff:"easy"},
  {q:"¿Quién canta 'Shape of You'?",                   a:["Justin Bieber","Bruno Mars","Ed Sheeran","Harry Styles"],c:2,cat:"ent",diff:"easy"},
  {q:"¿Quién interpreta a Jack Sparrow?",               a:["Brad Pitt","Johnny Depp","Orlando Bloom","Keira Knightley"],c:1,cat:"ent",diff:"easy"},
  {q:"¿Qué personaje de cómic es Bruce Wayne?",         a:["Superman","Spider-Man","Batman","Iron Man"],    c:2, cat:"ent",  diff:"easy"},
  {q:"¿Cuántas temporadas tiene 'Friends'?",            a:["8","9","10","11"],                              c:2, cat:"ent",  diff:"easy"},
  {q:"¿Qué grupo musical son Freddie Mercury, Brian May, Roger Taylor y John Deacon?",a:["The Beatles","Led Zeppelin","Queen","Pink Floyd"],c:2,cat:"ent",diff:"easy"},
  {q:"¿Cuántas novelas hay en la saga 'Harry Potter'?", a:["5","6","7","8"],                               c:2, cat:"ent",  diff:"easy"},
  {q:"¿Qué película animada presenta a la princesa Moana?",a:["Vaiana","Brave","Enredados","Frozen"],       c:0, cat:"ent",  diff:"easy"},
  {q:"¿Quién canta 'Blinding Lights'?",                 a:["Drake","Travis Scott","The Weeknd","Post Malone"],c:2,cat:"ent",diff:"easy"},
  {q:"¿Qué serie narra la historia de Walter White?",   a:["Ozark","Narcos","Breaking Bad","Better Call Saul"],c:2,cat:"ent",diff:"easy"},
  {q:"¿Qué fruto es el aguacate?",                      a:["Verdura","Legumbre","Fruta","Tubérculo"],        c:2, cat:"food", diff:"easy"},
  {q:"¿De qué país es el ceviche?",                     a:["México","Colombia","Perú","Chile"],              c:2, cat:"food", diff:"easy"},
  {q:"¿Cuál es la base del pan de molde?",              a:["Maíz","Centeno","Trigo","Espelta"],              c:2, cat:"food", diff:"easy"},
  {q:"¿De qué país es el bacalao a la vizcaína?",       a:["Portugal","Noruega","España","Francia"],         c:2, cat:"food", diff:"easy"},
  {q:"¿Qué bebida es el mate?",                         a:["Tipo de té","Infusión de yerba mate","Cerveza local","Refresco"],c:1,cat:"food",diff:"easy"},
  {q:"¿Cuántas uvas se comen en España en Nochevieja?", a:["10","12","13","15"],                             c:1, cat:"food", diff:"easy"},
  // ── TECNOLOGÍA (nuevas) ──
  {q:"¿Qué significa CPU?",                            a:["Central Processing Unit","Computer Power Unit","Core Processor Utility","Central Program Unit"],c:0,cat:"tech",diff:"easy"},
  {q:"¿Qué lenguaje usa principalmente el desarrollo web front-end?",a:["Python","Java","JavaScript","C#"],c:2,cat:"tech",diff:"easy"},
  {q:"¿Qué significa GPS?",                            a:["Global Positioning System","General Processing Software","Graphic Position Service","Global Phone System"],c:0,cat:"tech",diff:"easy"},
  {q:"¿Qué significa RAM?",                            a:["Random Access Memory","Read All Memory","Rapid Access Module","Real Allocated Memory"],c:0,cat:"tech",diff:"easy"},
  {q:"¿Qué empresa fabrica la consola PlayStation?",   a:["Microsoft","Nintendo","Sony","Sega"],            c:2, cat:"tech", diff:"easy"},
  {q:"¿Qué sistema operativo usa el iPhone?",          a:["Android","HarmonyOS","iOS","Windows Phone"],     c:2, cat:"tech", diff:"easy"},
  {q:"¿Qué empresa fundó Elon Musk dedicada a cohetes?",a:["Blue Origin","Virgin Galactic","SpaceX","Boeing"],c:2,cat:"tech",diff:"easy"},
  {q:"¿Cuál es el lenguaje de programación más usado en inteligencia artificial?",a:["Java","C++","Python","R"],c:2,cat:"tech",diff:"easy"},
  {q:"¿Cuántos tipos de grupos sanguíneos hay en el sistema ABO?",a:["2","3","4","5"],                     c:2, cat:"sci",  diff:"easy"},
  {q:"¿Qué órgano filtra la sangre en el cuerpo?",     a:["Hígado","Bazo","Riñón","Pulmón"],               c:2, cat:"sci",  diff:"easy"},
  // ── HISTORIA EXTRA ──
  {q:"¿Quién fue el primer rey de España tras la Transición?",a:["Carlos I","Felipe VI","Juan Carlos I","Alfonso XIII"],c:2,cat:"hist",diff:"easy"},
  {q:"¿En qué continente está el río Nilo?",            a:["Asia","Europa","África","América"],             c:2, cat:"geo",  diff:"easy"},
  {q:"¿En qué país está el Amazonas (la mayor parte)?", a:["Perú","Colombia","Brasil","Venezuela"],         c:2, cat:"geo",  diff:"easy"},
  {q:"¿Qué mar está entre Europa y África?",            a:["Mar Rojo","Mar Negro","Mar Mediterráneo","Mar del Norte"],c:2,cat:"geo",diff:"easy"},

  // ── GEOGRAFÍA (nuevas x100) ──
  {q:"¿Cuál es la capital de Francia?",                 a:["Lyon","Marsella","París","Burdeos"],                c:2, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es la capital de Alemania?",                a:["Múnich","Hamburgo","Berlín","Frankfurt"],           c:2, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es la capital de Italia?",                  a:["Milán","Nápoles","Venecia","Roma"],                 c:3, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es la capital de España?",                  a:["Barcelona","Valencia","Sevilla","Madrid"],          c:3, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es la capital de México?",                  a:["Guadalajara","Monterrey","Ciudad de México","Puebla"], c:2, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es la capital de China?",                   a:["Shanghái","Pekín","Hong Kong","Cantón"],            c:1, cat:"geo",  diff:"easy"},
  {q:"¿En qué continente está Brasil?",                 a:["África","América del Norte","Europa","América del Sur"], c:3, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es el país más poblado de África?",         a:["Sudáfrica","Etiopía","Egipto","Nigeria"],           c:3, cat:"geo",  diff:"easy"},
  {q:"¿Qué océano está entre América y Europa?",        a:["Pacífico","Índico","Ártico","Atlántico"],           c:3, cat:"geo",  diff:"easy"},
  {q:"¿En qué país está la Torre Eiffel?",              a:["Bélgica","Suiza","Italia","Francia"],               c:3, cat:"geo",  diff:"easy"},
  {q:"¿En qué país está la Gran Muralla China?",        a:["Japón","Corea","Mongolia","China"],                 c:3, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es el continente más grande del mundo?",    a:["América","África","Asia","Europa"],                 c:2, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es el continente más pequeño del mundo?",   a:["Europa","Oceanía","Antártida","África"],            c:1, cat:"geo",  diff:"easy"},
  {q:"¿En qué país está el Coliseo?",                   a:["Grecia","España","Francia","Italia"],               c:3, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es la capital de Portugal?",                a:["Oporto","Braga","Faro","Lisboa"],                   c:3, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es la capital de Rusia?",                   a:["San Petersburgo","Moscú","Kazán","Novosibirsk"],    c:1, cat:"geo",  diff:"easy"},
  {q:"¿Cuántos países tiene Europa aproximadamente?",   a:["30","40","50","60"],                                c:2, cat:"geo",  diff:"easy"},
  {q:"¿Qué país comparte frontera con España al norte?",a:["Portugal","Francia","Andorra","Los dos últimos"],   c:3, cat:"geo",  diff:"easy"},
  {q:"¿En qué continente está la selva amazónica?",     a:["África","Asia","América del Sur","Oceanía"],        c:2, cat:"geo",  diff:"easy"},
  {q:"¿Cuál es la capital de Grecia?",                  a:["Tesalónica","Creta","Corinto","Atenas"],            c:3, cat:"geo",  diff:"easy"},

  // ── CIENCIA (nuevas x100) ──
  {q:"¿Cuántos ojos tiene una araña típica?",           a:["2","4","6","8"],                                    c:3, cat:"sci",  diff:"easy"},
  {q:"¿Qué animal es el más grande del mundo?",         a:["Elefante","Tiburón ballena","Ballena azul","Orca"], c:2, cat:"sci",  diff:"easy"},
  {q:"¿Cuántas patas tiene un insecto?",                a:["4","6","8","10"],                                   c:1, cat:"sci",  diff:"easy"},
  {q:"¿De qué está hecha la mayor parte del cuerpo humano?",a:["Grasa","Calcio","Agua","Proteínas"],            c:2, cat:"sci",  diff:"easy"},
  {q:"¿Qué planeta tiene el día más largo del sistema solar?",a:["Júpiter","Saturno","Venus","Marte"],          c:2, cat:"sci",  diff:"easy"},
  {q:"¿Cuántos segundos tiene un minuto?",              a:["10","30","60","100"],                               c:2, cat:"sci",  diff:"easy"},
  {q:"¿Qué sentido usa principalmente el murciélago para orientarse?",a:["Vista","Olfato","Ecolocalización","Tacto"], c:2, cat:"sci",  diff:"easy"},
  {q:"¿Cómo se llama la capa de gas que rodea la Tierra?",a:["Litosfera","Hidrosfera","Atmósfera","Biosfera"],  c:2, cat:"sci",  diff:"easy"},
  {q:"¿Qué tipo de animal es una ballena?",             a:["Pez","Anfibio","Reptil","Mamífero"],                c:3, cat:"sci",  diff:"easy"},
  {q:"¿Cuántos lados tiene un triángulo?",              a:["2","3","4","5"],                                    c:1, cat:"sci",  diff:"easy"},
  {q:"¿Qué planeta es conocido como el planeta rojo?",  a:["Júpiter","Venus","Marte","Saturno"],                c:2, cat:"sci",  diff:"easy"},
  {q:"¿Cuál es el símbolo químico del agua?",           a:["O2","CO2","H2O","NaCl"],                            c:2, cat:"sci",  diff:"easy"},
  {q:"¿Cuántos minutos tiene una hora?",                a:["30","45","60","90"],                                c:2, cat:"sci",  diff:"easy"},
  {q:"¿Qué fuerza nos mantiene pegados al suelo?",      a:["Magnetismo","Fricción","Gravedad","Tensión"],       c:2, cat:"sci",  diff:"easy"},
  {q:"¿Qué necesitan las plantas para hacer la fotosíntesis?",a:["Sal y agua","Luz y CO₂","Viento y lluvia","Tierra y arena"], c:1, cat:"sci",  diff:"easy"},

  // ── HISTORIA (nuevas x100) ──
  {q:"¿Quién fue el último zar de Rusia?",              a:["Alejandro III","Nicolás I","Nicolás II","Pablo I"], c:2, cat:"hist", diff:"easy"},
  {q:"¿En qué año se fundó Roma, según la tradición?",  a:["753 a.C.","500 a.C.","1000 a.C.","200 a.C."],      c:0, cat:"hist", diff:"easy"},
  {q:"¿Quién fue el primer faraón de Egipto?",          a:["Tutankamón","Ramsés II","Narmer","Cleopatra"],      c:2, cat:"hist", diff:"easy"},
  {q:"¿Qué guerra enfrentó a la Unión y la Confederación?",a:["Primera Guerra Mundial","Guerra Civil Americana","Guerra de Secesión Francesa","Guerra de los Siete Años"], c:1, cat:"hist", diff:"easy"},
  {q:"¿En qué año terminó la Primera Guerra Mundial?",  a:["1916","1917","1918","1919"],                        c:2, cat:"hist", diff:"easy"},
  {q:"¿Qué país construyó el Imperio Romano?",          a:["Grecia","Egipto","Persia","Italia"],                c:3, cat:"hist", diff:"easy"},
  {q:"¿En qué continente nació la civilización griega?",a:["Asia","América","África","Europa"],                 c:3, cat:"hist", diff:"easy"},
  {q:"¿Quién fue Nelson Mandela?",                      a:["Primer ministro de Kenia","Presidente de Nigeria","Presidente de Sudáfrica","Rey de Etiopía"], c:2, cat:"hist", diff:"easy"},
  {q:"¿En qué año se independizó EE.UU. de Gran Bretaña?",a:["1776","1783","1800","1812"],                     c:0, cat:"hist", diff:"easy"},
  {q:"¿Cómo se llamaba el barco en el que viajó Colón?",a:["Victoria","Beagle","Santa María","Pinta"],         c:2, cat:"hist", diff:"easy"},

  // ── ARTE Y CULTURA (nuevas x100) ──
  {q:"¿Cuántas cuerdas tiene una guitarra estándar?",   a:["4","5","6","7"],                                    c:2, cat:"art",  diff:"easy"},
  {q:"¿Quién escribió 'Romeo y Julieta'?",              a:["Dickens","Chaucer","Shakespeare","Milton"],         c:2, cat:"art",  diff:"easy"},
  {q:"¿Qué instrumento toca un pianista?",              a:["Violín","Trombón","Piano","Flauta"],                c:2, cat:"art",  diff:"easy"},
  {q:"¿En qué idioma se escribió 'El Quijote'?",        a:["Latín","Portugués","Español","Catalán"],            c:2, cat:"art",  diff:"easy"},
  {q:"¿Quién compuso 'Para Elisa'?",                    a:["Mozart","Chopin","Bach","Beethoven"],               c:3, cat:"art",  diff:"easy"},
  {q:"¿Qué color se obtiene mezclando rojo y amarillo?",a:["Verde","Morado","Naranja","Marrón"],                c:2, cat:"art",  diff:"easy"},
  {q:"¿Cuántos colores primarios existen (modelo tradicional)?",a:["2","3","4","5"],                            c:1, cat:"art",  diff:"easy"},
  {q:"¿Quién creó el personaje de James Bond literariamente?",a:["John le Carré","Ian Fleming","Tom Clancy","Frederick Forsyth"], c:1, cat:"art",  diff:"easy"},
  {q:"¿De qué país es el baile del tango?",             a:["Brasil","Cuba","España","Argentina"],               c:3, cat:"art",  diff:"easy"},
  {q:"¿Qué escritor creó a Huckleberry Finn?",          a:["Ernest Hemingway","Mark Twain","Edgar Allan Poe","Jack London"], c:1, cat:"art",  diff:"easy"},
  {q:"¿Qué banda lanzó el álbum 'Thriller'?",           a:["Prince","Madonna","Michael Jackson","Janet Jackson"],c:2, cat:"art",  diff:"easy"},
  {q:"¿En qué país nació Mozart?",                      a:["Alemania","Suiza","Austria","Polonia"],             c:2, cat:"art",  diff:"easy"},
  {q:"¿Quién pintó 'El Guernica'?",                     a:["Dalí","Miró","Goya","Picasso"],                     c:3, cat:"art",  diff:"easy"},
  {q:"¿Cómo se llama la ópera más famosa de Verdi sobre un esclavo etíope?",a:["Carmen","Tosca","Aída","Rigoletto"], c:2, cat:"art",  diff:"easy"},
  {q:"¿Qué grupo es conocido como 'Los Fab Four'?",     a:["Queen","Rolling Stones","The Beatles","Led Zeppelin"], c:2, cat:"art",  diff:"easy"},

  // ── DEPORTE (nuevas x100) ──
  {q:"¿Cuántos puntos vale un gol en fútbol?",          a:["1","2","3","5"],                                    c:0, cat:"sport",diff:"easy"},
  {q:"¿Qué deporte se juega en Wimbledon?",             a:["Golf","Críquet","Tenis","Squash"],                  c:2, cat:"sport",diff:"easy"},
  {q:"¿Cuántos jugadores tiene un equipo de rugby union?",a:["11","13","15","17"],                              c:2, cat:"sport",diff:"easy"},
  {q:"¿En qué deporte se usa un bate y una pelota pequeña dura?",a:["Rugby","Béisbol","Hockey","Críquet"],      c:1, cat:"sport",diff:"easy"},
  {q:"¿Cuántas vueltas tiene una carrera de 400m en atletismo?",a:["1","2","4","8"],                            c:0, cat:"sport",diff:"easy"},
  {q:"¿En qué deporte compite Usain Bolt?",             a:["Natación","Atletismo","Ciclismo","Salto de altura"],c:1, cat:"sport",diff:"easy"},
  {q:"¿Cuántos sets se juegan como máximo en tenis femenino (Grand Slam)?",a:["3","4","5","6"],                 c:0, cat:"sport",diff:"easy"},
  {q:"¿Qué color es la tarjeta de expulsión en fútbol?",a:["Naranja","Verde","Roja","Azul"],                   c:2, cat:"sport",diff:"easy"},
  {q:"¿Cuántos jugadores hay en un equipo de béisbol?", a:["7","8","9","10"],                                   c:2, cat:"sport",diff:"easy"},
  {q:"¿En qué deporte se usa el término 'home run'?",   a:["Cricket","Golf","Béisbol","Softball"],              c:2, cat:"sport",diff:"easy"},

  // ── ENTRETENIMIENTO (nuevas x100) ──
  {q:"¿En qué ciudad transcurre 'Friends'?",            a:["Los Ángeles","Chicago","Nueva York","Boston"],      c:2, cat:"ent",  diff:"easy"},
  {q:"¿Qué personaje vive en la calle Sésamo?",         a:["Mickey Mouse","Elmo","Peppa Pig","Bob Esponja"],    c:1, cat:"ent",  diff:"easy"},
  {q:"¿Qué empresa fabrica la consola Xbox?",           a:["Sony","Nintendo","Microsoft","Sega"],               c:2, cat:"ent",  diff:"easy"},
  {q:"¿Cómo se llama el mayordomo de Batman?",          a:["Robin","Alfred","James","Gordon"],                  c:1, cat:"ent",  diff:"easy"},
  {q:"¿En qué película aparece el personaje de Gandalf?",a:["Narnia","Star Wars","El Señor de los Anillos","Harry Potter"], c:2, cat:"ent",  diff:"easy"},
  {q:"¿De qué color es el coche de Herbie?",            a:["Rojo con negro","Azul con blanco","Blanco con negro","Amarillo con negro"], c:2, cat:"ent",  diff:"easy"},
  {q:"¿Qué personaje de Disney es una sirena?",         a:["Rapunzel","Bella","La Sirenita","Elsa"],            c:2, cat:"ent",  diff:"easy"},
  {q:"¿Quién es el villano principal de 'El Rey León'?", a:["Rafiki","Pumba","Scar","Timón"],                   c:2, cat:"ent",  diff:"easy"},
  {q:"¿En qué año salió el primer juego de Super Mario Bros?",a:["1981","1983","1985","1987"],                  c:2, cat:"ent",  diff:"easy"},
  {q:"¿Cómo se llama el robot aspirador del universo Pixar que da nombre a su película?",a:["R2-D2","WALL-E","EVE","HAL"], c:1, cat:"ent",  diff:"easy"},
  {q:"¿Qué canción pop de Adele habla de llamar a un ex?",a:["Someone Like You","Rolling in the Deep","Hello","Skyfall"], c:2, cat:"ent",  diff:"easy"},
  {q:"¿En qué saga aparece el personaje de Katniss Everdeen?",a:["Divergente","Los Juegos del Hambre","Maze Runner","Crepúsculo"], c:1, cat:"ent",  diff:"easy"},
  {q:"¿Qué actor interpreta a Thor en el MCU?",         a:["Chris Evans","Chris Hemsworth","Tom Hiddleston","Chris Pratt"], c:1, cat:"ent",  diff:"easy"},
  {q:"¿Qué animal es Pikachu?",                         a:["Ratón","Conejo","Perro","Zorro"],                   c:0, cat:"ent",  diff:"easy"},
  {q:"¿Cómo se llama el protagonista de 'The Witcher'?",a:["Geralt","Ciri","Yennefer","Jaskier"],               c:0, cat:"ent",  diff:"easy"},

  // ── GASTRONOMÍA (nuevas x100) ──
  {q:"¿De qué país es el plato llamado 'fish and chips'?",a:["Australia","Irlanda","EE.UU.","Reino Unido"],     c:3, cat:"food", diff:"easy"},
  {q:"¿Cuál es el ingrediente principal de la tortilla española?",a:["Harina","Arroz","Huevo y patata","Leche"], c:2, cat:"food", diff:"easy"},
  {q:"¿De qué país es el plato 'moussaka'?",            a:["Italia","Turquía","España","Grecia"],               c:3, cat:"food", diff:"easy"},
  {q:"¿Qué fruta es de color amarillo y se pela antes de comer?",a:["Naranja","Uva","Plátano","Sandía"],        c:2, cat:"food", diff:"easy"},
  {q:"¿De qué animal se obtiene la leche que se usa habitualmente?",a:["Cerdo","Gallina","Vaca","Oveja"],       c:2, cat:"food", diff:"easy"},
  {q:"¿Qué verdura es conocida como 'el rey de las verduras' por su sabor amargo?",a:["Lechuga","Espinaca","Coles de Bruselas","Alcachofa"], c:3, cat:"food", diff:"easy"},
  {q:"¿Cuál es el ingrediente base del pan?",           a:["Arroz","Maíz","Trigo (harina)","Avena"],            c:2, cat:"food", diff:"easy"},
  {q:"¿De qué país es la pizza Margarita original?",    a:["España","Italia","Francia","Grecia"],               c:1, cat:"food", diff:"easy"},
  {q:"¿Qué bebida caliente se prepara con hojas secas en agua?",a:["Café","Chocolate","Zumo","Té"],             c:3, cat:"food", diff:"easy"},
  {q:"¿Con qué fruta se hace la mermelada de naranja?", a:["Limón","Naranja","Mandarina","Pomelo"],             c:1, cat:"food", diff:"easy"},

  // ── TECNOLOGÍA (nuevas x100) ──
  {q:"¿Qué significa 'www' al inicio de una web?",      a:["World Wide Web","Wide World Web","Web World Wide","World Web Wide"], c:0, cat:"tech", diff:"easy"},
  {q:"¿Cuántos colores tiene el logo de Google?",        a:["3","4","5","6"],                                   c:1, cat:"tech", diff:"easy"},
  {q:"¿Qué significa 'HD' en calidad de vídeo?",        a:["High Download","Heavy Definition","High Definition","Hard Drive"], c:2, cat:"tech", diff:"easy"},
  {q:"¿Qué empresa creó el buscador más usado del mundo?",a:["Microsoft","Apple","Amazon","Google"],            c:3, cat:"tech", diff:"easy"},
];
