/* ═══════════════════════════════════════════════════
   questions_medium.js — Preguntas de dificultad MEDIA
   diff: "med"

   Para añadir preguntas medias:
     {q:"pregunta", a:["op1","op2","op3","op4"], c:índice_correcto, cat:"cat", diff:"med"}

   Categorías disponibles: geo, sci, hist, art, sport, ent, food, tech
═══════════════════════════════════════════════════ */

const QUESTIONS_MEDIUM = [
  {q:"¿Cuál es la capital de Australia?",              a:["Sídney","Melbourne","Brisbane","Canberra"],      c:3, cat:"geo",  diff:"med"},
  {q:"¿En qué país nace el río Amazonas?",             a:["Brasil","Perú","Colombia","Ecuador"],            c:1, cat:"geo",  diff:"med"},
  {q:"¿Cuál es la capital de Canadá?",                a:["Toronto","Montreal","Vancouver","Ottawa"],       c:3, cat:"geo",  diff:"med"},
  {q:"¿En qué país está el Monte Kilimanjaro?",        a:["Kenia","Uganda","Tanzania","Etiopía"],           c:2, cat:"geo",  diff:"med"},
  {q:"¿Cuál es la capital de Brasil?",                a:["São Paulo","Río de Janeiro","Brasilia","Salvador"],c:2,cat:"geo", diff:"med"},
  // ── CIENCIA ──
  {q:"¿Cuántos huesos tiene el cuerpo humano adulto?", a:["206","212","198","220"],                         c:0, cat:"sci",  diff:"med"},
  {q:"¿Cuál es el metal más abundante en la corteza?", a:["Hierro","Aluminio","Cobre","Silicio"],          c:1, cat:"sci",  diff:"med"},
  {q:"¿Qué órgano del cuerpo produce la insulina?",    a:["Hígado","Riñón","Páncreas","Estómago"],         c:2, cat:"sci",  diff:"med"},
  {q:"¿Cuántos cromosomas tiene una célula humana normal?",a:["23","44","46","48"],                        c:2, cat:"sci",  diff:"med"},
  {q:"¿Qué partícula no tiene carga eléctrica?",       a:["Protón","Electrón","Neutrón","Fotón"],           c:2, cat:"sci",  diff:"med"},
  {q:"¿A qué velocidad viaja la luz (aprox)?",         a:["150.000 km/s","300.000 km/s","500.000 km/s","1.000.000 km/s"],c:1,cat:"sci",diff:"med"},
  {q:"¿En qué año cayó el Muro de Berlín?",            a:["1987","1989","1991","1993"],                     c:1, cat:"hist", diff:"med"},
  {q:"¿Quién fue el faraón que ordenó construir la Gran Pirámide?",a:["Tutankamón","Ramsés II","Keops","Nefertiti"],c:2,cat:"hist",diff:"med"},
  {q:"¿En qué año tuvo lugar la Revolución Francesa?", a:["1776","1789","1804","1815"],                     c:1, cat:"hist", diff:"med"},
  {q:"¿En qué siglo ocurrió la Revolución Industrial?",a:["XVII","XVIII","XIX","XX"],                      c:1, cat:"hist", diff:"med"},
  {q:"¿Cuál es el idioma más hablado del mundo?",      a:["Inglés","Español","Hindi","Mandarín"],           c:3, cat:"art",  diff:"med"},
  {q:"¿Dónde está el cuadro de La última cena de Da Vinci?",a:["Roma","París","Milán","Florencia"],        c:2, cat:"art",  diff:"med"},
  {q:"¿Quién esculpió El David (Florencia)?",          a:["Rafael","Da Vinci","Miguel Ángel","Donatello"],  c:2, cat:"art",  diff:"med"},
  {q:"¿En qué museo está la Venus de Milo?",           a:["Uffizi","Metropolitan","Louvre","Prado"],        c:2, cat:"art",  diff:"med"},
  {q:"¿Cuántos sets gana un partido de tenis (Grand Slam masculino)?",a:["2","3","4","5"],                  c:1, cat:"sport",diff:"med"},
  {q:"¿En qué deporte se usa un birdie?",              a:["Béisbol","Golf","Tenis","Críquet"],              c:1, cat:"sport",diff:"med"},
  {q:"¿En qué año se celebraron los Juegos Olímpicos de Barcelona?",a:["1988","1990","1992","1996"],        c:2, cat:"sport",diff:"med"},
  {q:"¿En qué ciudad se celebraron los JJ.OO. de 2021?",a:["París","Londres","Tokio","Pekín"],             c:2, cat:"sport",diff:"med"},
  {q:"¿En qué año se lanzó el primer iPhone?",         a:["2005","2007","2009","2010"],                     c:1, cat:"ent",  diff:"med"},
  {q:"¿Cuántas temporadas tiene Breaking Bad?",        a:["4","5","6","7"],                                 c:1, cat:"ent",  diff:"med"},
  {q:"¿De qué país es el kimchi?",                     a:["China","Japón","Tailandia","Corea"],             c:3, cat:"food", diff:"med"},
  {q:"¿Cuál es el principal ingrediente del hummus?",  a:["Lentejas","Garbanzos","Judías","Habas"],         c:1, cat:"food", diff:"med"},
  {q:"¿Qué significa HTML?",                           a:["HyperText Markup Language","HyperText Modern Language","High-Tech Machine Learning","HyperText Media Link"],c:0,cat:"tech",diff:"med"},
  {q:"¿En qué año se fundó Google?",                   a:["1994","1996","1998","2000"],                     c:2, cat:"tech", diff:"med"},
  {q:"¿Cuál es el país más pequeño del mundo?",        a:["Mónaco","San Marino","Liechtenstein","Vaticano"],c:3, cat:"geo",  diff:"med"},
  {q:"¿Cuál es el río más largo de Europa?",           a:["Rin","Danubio","Volga","Sena"],                  c:2, cat:"geo",  diff:"med"},
  {q:"¿Cuál es la capital de Turquía?",                a:["Estambul","Esmirna","Ankara","Bursa"],           c:2, cat:"geo",  diff:"med"},
  {q:"¿Cuántos países tiene América del Sur?",         a:["10","12","14","16"],                             c:1, cat:"geo",  diff:"med"},
  {q:"¿En qué país está la Patagonia?",                a:["Chile","Bolivia","Argentina y Chile","Perú"],    c:2, cat:"geo",  diff:"med"},
  {q:"¿Qué país tiene más habitantes del mundo?",      a:["India","China","EE.UU.","Indonesia"],            c:0, cat:"geo",  diff:"med"},
  {q:"¿En qué continente está Kazajistán?",            a:["Europa","Asia","África","Oceanía"],              c:1, cat:"geo",  diff:"med"},
  {q:"¿Cuál es la capital de Nueva Zelanda?",          a:["Auckland","Christchurch","Wellington","Hamilton"],c:2,cat:"geo",diff:"med"},
  {q:"¿Cuál es el símbolo del hierro en la tabla periódica?",a:["Fe","Fr","Ir","In"],                       c:0, cat:"sci",  diff:"med"},
  {q:"¿Qué tipo de onda es la luz?",                   a:["Mecánica","Sonora","Electromagnética","Gravitacional"],c:2,cat:"sci",diff:"med"},
  {q:"¿Cuál es la unidad de medida de la corriente?",  a:["Voltio","Ohmio","Amperio","Vatio"],              c:2, cat:"sci",  diff:"med"},
  {q:"¿Cuántas capas tiene la Tierra?",                a:["2","3","4","5"],                                 c:2, cat:"sci",  diff:"med"},
  {q:"¿Qué planeta está más lejos del Sol?",           a:["Saturno","Urano","Neptuno","Plutón"],            c:2, cat:"sci",  diff:"med"},
  {q:"¿Qué significa pH?",                             a:["Potencial Hidrógeno","Potencial Helio","Porcentaje Hídrico","Presión Hidráulica"],c:0,cat:"sci",diff:"med"},
  // ── HISTORIA (nuevas) ──
  {q:"¿En qué año se descubrió la penicilina?",        a:["1918","1923","1928","1935"],                     c:2, cat:"hist", diff:"med"},
  {q:"¿Qué guerra terminó con el Tratado de Versalles?",a:["Primera Guerra Mundial","Segunda Guerra Mundial","Guerra de Crimea","Guerra de los Cien Años"],c:0,cat:"hist",diff:"med"},
  {q:"¿En qué año se inventó la imprenta (Gutenberg)?",a:["1340","1440","1540","1640"],                    c:1, cat:"hist", diff:"med"},
  {q:"¿En qué año tuvo lugar la Revolución Rusa?",     a:["1905","1914","1917","1921"],                    c:2, cat:"hist", diff:"med"},
  {q:"¿Quién fue el primer presidente de España en democracia?",a:["Felipe González","Adolfo Suárez","Leopoldo Calvo-Sotelo","Santiago Carrillo"],c:1,cat:"hist",diff:"med"},
  {q:"¿Quién compuso 'Las cuatro estaciones'?",        a:["Bach","Vivaldi","Mozart","Handel"],              c:1, cat:"art",  diff:"med"},
  {q:"¿Qué movimiento artístico lideró Picasso?",      a:["Impresionismo","Surrealismo","Cubismo","Dadaísmo"],c:2,cat:"art",diff:"med"},
  {q:"¿Cuántas sinfonías compuso Beethoven?",          a:["7","8","9","10"],                                c:2, cat:"art",  diff:"med"},
  {q:"¿Qué arquitecto diseñó el Guggenheim de Bilbao?",a:["Renzo Piano","Norman Foster","Frank Gehry","Zaha Hadid"],c:2,cat:"art",diff:"med"},
  {q:"¿Quién escribió 'Fahrenheit 451'?",              a:["George Orwell","Aldous Huxley","Ray Bradbury","Philip K. Dick"],c:2,cat:"art",diff:"med"},
  {q:"¿Qué estilo musical es originario de Nueva Orleans?",a:["Blues","Jazz","Rock","Soul"],               c:1, cat:"art",  diff:"med"},
  {q:"¿En qué deporte se compite por el Trofeo Davis?", a:["Golf","Tenis","Béisbol","Squash"],              c:1, cat:"sport",diff:"med"},
  {q:"¿Qué equipo ha ganado más Champions League?",     a:["Barcelona","Bayern","AC Milan","Real Madrid"],  c:3, cat:"sport",diff:"med"},
  {q:"¿Cuántos metros tiene la maratón?",               a:["40.000","41.195","42.195","43.195"],            c:2, cat:"sport",diff:"med"},
  {q:"¿Qué atleta tiene más medallas olímpicas de la historia?",a:["Usain Bolt","Michael Phelps","Carl Lewis","Mark Spitz"],c:1,cat:"sport",diff:"med"},
  {q:"¿En qué ciudad se celebraron los primeros JJ.OO. modernos?",a:["París","Londres","Atenas","Roma"],   c:2, cat:"sport",diff:"med"},
  {q:"¿En qué deporte se usa un guante de bateo?",      a:["Béisbol","Softball","Criquet","Los dos primeros"],c:3,cat:"sport",diff:"med"},
  {q:"¿Qué serie tiene el capítulo más visto de la historia de HBO?",a:["Los Soprano","The Wire","Game of Thrones","Succession"],c:2,cat:"ent",diff:"med"},
  {q:"¿Qué película ganó el Oscar a mejor película en 2020?",a:["1917","Joker","Parásitos","Ford v Ferrari"],c:2,cat:"ent",diff:"med"},
  {q:"¿En qué año salió el videojuego 'The Last of Us'?",a:["2011","2013","2015","2017"],                  c:1, cat:"ent",  diff:"med"},
  {q:"¿Qué videojuego tiene el personaje Master Chief?",a:["Destiny","Halo","Call of Duty","Gears of War"], c:1, cat:"ent",  diff:"med"},
  {q:"¿Quién compuso la banda sonora de Star Wars?",    a:["Hans Zimmer","John Williams","Ennio Morricone","Howard Shore"],c:1,cat:"ent",diff:"med"},
  {q:"¿En qué país se produjo la serie 'Dark'?",        a:["EE.UU.","Francia","Alemania","España"],         c:2, cat:"ent",  diff:"med"},
  {q:"¿Qué consola lanzó Sony como rival de la N64?",   a:["Dreamcast","PlayStation","Saturn","GameCube"],  c:1, cat:"ent",  diff:"med"},
  // ── GASTRONOMÍA (nuevas) ──
  {q:"¿De qué país es la fondue de queso?",             a:["Francia","Austria","Suiza","Alemania"],          c:2, cat:"food", diff:"med"},
  {q:"¿Qué es el Roquefort?",                           a:["Vino francés","Queso azul","Embutido","Salsa"],  c:1, cat:"food", diff:"med"},
  {q:"¿Qué especia da color amarillo al curry?",        a:["Cúrcuma","Comino","Jengibre","Canela"],          c:0, cat:"food", diff:"med"},
  {q:"¿Qué es el prosciutto?",                          a:["Queso italiano","Jamón curado italiano","Pasta rellena","Salsa de tomate"],c:1,cat:"food",diff:"med"},
  {q:"¿Cuándo se fundó Apple?",                        a:["1974","1976","1978","1980"],                     c:1, cat:"tech", diff:"med"},
  {q:"¿Qué empresa creó el procesador M1?",            a:["Intel","AMD","Qualcomm","Apple"],                c:3, cat:"tech", diff:"med"},
  {q:"¿Cuántos GB tiene 1 TB?",                        a:["100","512","1000","1024"],                       c:3, cat:"tech", diff:"med"},
  {q:"¿Quién creó Linux?",                             a:["Bill Gates","Steve Jobs","Linus Torvalds","Richard Stallman"],c:2,cat:"tech",diff:"med"},
  {q:"¿Qué significa URL?",                            a:["Universal Resource Locator","Uniform Resource Locator","Unique Reference Link","Universal Routing Language"],c:1,cat:"tech",diff:"med"},
  {q:"¿Cuánto tarda la luz en llegar del Sol a la Tierra?",a:["2 minutos","8 minutos","15 minutos","1 hora"],c:1,cat:"sci",diff:"med"},
  {q:"¿Cuántos elementos hay en la tabla periódica actual?",a:["108","110","118","120"],                    c:2, cat:"sci",  diff:"med"},
  {q:"¿Qué tipo de animal es una orca?",               a:["Tiburón","Delfín grande","Ballena dentada","Pez espada"],c:1,cat:"sci",diff:"med"},
  {q:"¿Qué tratado puso fin a la Primera Guerra Mundial?",a:["Versalles","Utrecht","Westfalia","París"],    c:0, cat:"hist", diff:"med"},
  {q:"¿Quién fue Adolf Hitler antes de ser político?",  a:["Escritor","Militar","Pintor","Arquitecto"],    c:2, cat:"hist", diff:"med"},
  {q:"¿En qué año se abolió la esclavitud en EE.UU.?", a:["1860","1863","1865","1870"],                    c:2, cat:"hist", diff:"med"},
  {q:"¿Qué ciudad es la más poblada del mundo?",        a:["Shanghái","Delhi","Tokio","São Paulo"],         c:2, cat:"geo",  diff:"med"},
];
